In [ ]:
!pip install faker

Collecting faker
  Downloading faker-40.32.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.32.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 30.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.32.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/AML_Project"

In [ ]:
import pandas as pd
import random
from faker import Faker

fake = Faker("en_IN")

random.seed(42)

In [ ]:
cities_df = pd.read_csv("cities.csv")

cities_df.head()

   city_id       city        state  latitude  longitude  population country
0  CITY001      Delhi        Delhi   28.6139    77.2090    33000000   India
1  CITY002     Mumbai  Maharashtra   19.0760    72.8777    21000000   India
2  CITY003  Bengaluru    Karnataka   12.9716    77.5946    14000000   India
3  CITY004    Chennai   Tamil Nadu   13.0827    80.2707    11000000   India
4  CITY005  Hyderabad    Telangana   17.3850    78.4867    10500000   India

In [ ]:
occupations = {
    "Student": (10000, 30000),
    "Engineer": (50000, 120000),
    "Doctor": (80000, 300000),
    "Teacher": (30000, 70000),
    "Business": (100000, 500000),
    "Government Employee": (40000, 100000),
    "Lawyer": (70000, 250000),
    "Freelancer": (20000, 150000),
    "Retired": (15000, 50000),
    "Shop Owner": (30000, 150000)
}

In [ ]:
transaction_preferences = {
    "Student": ["UPI", "Shopping", "Food", "Recharge"],
    "Engineer": ["UPI", "Card", "Fuel", "Shopping"],
    "Doctor": ["Transfer", "Card", "Investment"],
    "Teacher": ["UPI", "ATM", "Bills"],
    "Business": ["Transfer", "NEFT", "RTGS", "Salary"],
    "Government Employee": ["UPI", "Bills", "ATM"],
    "Lawyer": ["Transfer", "Card"],
    "Freelancer": ["UPI", "Transfer"],
    "Retired": ["ATM", "Bills"],
    "Shop Owner": ["UPI", "Transfer", "Cash Deposit"]
}

In [ ]:
num_customers = 5000

customers = []

for i in range(1, num_customers + 1):

    city = cities_df.sample(1).iloc[0]

    occupation = random.choice(list(occupations.keys()))

    income = random.randint(
        occupations[occupation][0],
        occupations[occupation][1]
    )

    age = random.randint(18, 70)

    gender = random.choice(["Male", "Female"])

    # Only 5% suspicious customers
    risk = random.choices(
        ["Normal", "Suspicious"],
        weights=[95,5]
    )[0]

    customers.append({

        "customer_id": f"CUST{i:05d}",

        "name": fake.name(),

        "age": age,

        "gender": gender,

        "occupation": occupation,

        "monthly_income": income,

        "city_id": city["city_id"],

        "city": city["city"],

        "state": city["state"],

        "country": city["country"],

        "home_latitude": city["latitude"],

        "home_longitude": city["longitude"],

        "preferred_transactions":
            ", ".join(transaction_preferences[occupation]),

        "avg_transactions_per_day":
            random.randint(2,15),

        "risk_label": risk

    })

In [ ]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,customer_id,name,age,gender,occupation,monthly_income,city_id,city,state,country,home_latitude,home_longitude,preferred_transactions,avg_transactions_per_day,risk_label
0,CUST00001,Gautami Wagle,65,Female,Engineer,53278,CITY008,Ahmedabad,Gujarat,India,23.0225,72.5714,"UPI, Card, Fuel, Shopping",4,Normal
1,CUST00002,Girik Bhatia,55,Female,Engineer,61395,CITY019,Coimbatore,Tamil Nadu,India,11.0168,76.9558,"UPI, Card, Fuel, Shopping",3,Normal
2,CUST00003,Aadhya Dhillon,50,Male,Teacher,45247,CITY010,Lucknow,Uttar Pradesh,India,26.8467,80.9462,"UPI, ATM, Bills",13,Normal
3,CUST00004,Ryan Thaman,32,Female,Retired,42493,CITY012,Kanpur,Uttar Pradesh,India,26.4499,80.3319,"ATM, Bills",14,Normal
4,CUST00005,Amol Mann,62,Female,Student,15231,CITY003,Bengaluru,Karnataka,India,12.9716,77.5946,"UPI, Shopping, Food, Recharge",4,Normal

In [ ]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,customer_id,name,age,gender,occupation,monthly_income,city_id,city,state,country,home_latitude,home_longitude,preferred_transactions,avg_transactions_per_day,risk_label
0,CUST00001,Gautami Wagle,65,Female,Engineer,53278,CITY008,Ahmedabad,Gujarat,India,23.0225,72.5714,"UPI, Card, Fuel, Shopping",4,Normal
1,CUST00002,Girik Bhatia,55,Female,Engineer,61395,CITY019,Coimbatore,Tamil Nadu,India,11.0168,76.9558,"UPI, Card, Fuel, Shopping",3,Normal
2,CUST00003,Aadhya Dhillon,50,Male,Teacher,45247,CITY010,Lucknow,Uttar Pradesh,India,26.8467,80.9462,"UPI, ATM, Bills",13,Normal
3,CUST00004,Ryan Thaman,32,Female,Retired,42493,CITY012,Kanpur,Uttar Pradesh,India,26.4499,80.3319,"ATM, Bills",14,Normal
4,CUST00005,Amol Mann,62,Female,Student,15231,CITY003,Bengaluru,Karnataka,India,12.9716,77.5946,"UPI, Shopping, Food, Recharge",4,Normal

In [ ]:
customers_df.to_csv(
    f"{PROJECT_PATH}/dataset/customers.csv",
    index=False
)

print("Customers Dataset Created Successfully")

print()

print(customers_df.head())

print()

print("Total Customers :", len(customers_df))

print()

print(customers_df["risk_label"].value_counts())

Customers Dataset Created Successfully

  customer_id            name  age  gender occupation  monthly_income  \
0   CUST00001   Gautami Wagle   65  Female   Engineer           53278
1   CUST00002    Girik Bhatia   55  Female   Engineer           61395
2   CUST00003  Aadhya Dhillon   50    Male    Teacher           45247
3   CUST00004     Ryan Thaman   32  Female    Retired           42493
4   CUST00005       Amol Mann   62  Female    Student           15231

   city_id        city          state country  home_latitude  home_longitude  \
0  CITY008   Ahmedabad        Gujarat   India        23.0225         72.5714
1  CITY019  Coimbatore     Tamil Nadu   India        11.0168         76.9558
2  CITY010     Lucknow  Uttar Pradesh   India        26.8467         80.9462
3  CITY012      Kanpur  Uttar Pradesh   India        26.4499         80.3319
4  CITY003   Bengaluru      Karnataka   India        12.9716         77.5946

          preferred_transactions  avg_transactions_per_day risk_label
0      UPI, Card, Fuel, Shopping                         4     Normal
1      UPI, Card, Fuel, Shopping                         3     Normal
2                UPI, ATM, Bills                        13     Normal
3                     ATM, Bills                        14     Normal
4  UPI, Shopping, Food, Recharge                         4     Normal

Total Customers : 5000

risk_label
Normal        4739
Suspicious     261
Name: count, dtype: int64